apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-web-api-sample
  title: dot net meta ai 5
spec:
  type: service
  parameters:
       required:
         - name
       properties:
        name:
          title: Project Name
          type: string
          description: The name of the project
          default: dotnet-web-api-sample
  steps:
    - id: template
      name: Fetch template
      action: fetch:template
      input:
        url: https://github.com/glamperi/devspaces-dotnet-web-api-sample
        values:
          projectName: ${{ parameters.name }}
    
    
    - id: devspaces
      name: Create Dev Spaces workspace
      action: publish:custom
      input:
        provider: devspaces
        url: https://devspaces.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/dashboard/api/workspaces
        data:
          name: ${{ parameters.name }}
          description: Dev Spaces workspace for ${{ parameters.name }}
