apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-web-api-sample
  title: .NET Web API Sample
  description: A sample .NET Web API project
spec:
  owner: user1
  type: service
  parameters:
    - name: PROJECT_NAME
      description: The name of the project
      default: dotnet-web-api-sample
    - name: GIT_REPO_URL
      description: The URL of the Git repository
      default: https://github.com/glamperi/devspaces-dotnet-web-api-sample.git
    - name: GIT_BRANCH
      description: The branch of the Git repository
      default: main
  steps:
    - name: Create project
      action: exec:dotnet:new
      input:
        PROJECT_NAME: ${{ parameters.PROJECT_NAME }}
    - name: Build and run project
      action: exec:dotnet:run
      input:
        PROJECT_NAME: ${{ parameters.PROJECT_NAME }}

