apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-web-api-sample
  title: .NET Web API Sample
  description: A sample .NET Web API project - 5
spec:
  owner: user1
  type: service
  parameters:
    - name: PROJECT_NAME
      description: The name of the project
      default: dotnet-web-api-sample
    
  steps:
    - id: template
      name: Fetch template
      action: fetch:template
      input:
        url: https://github.com/glamperi/devspaces-dotnet-web-api-sample
        values:
          projectName: ${{ parameters.PROJECT_NAME }}
    - id: publish-gitops
      name: Publishing to Resource Repository
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.PROJECT_NAME}}"
        title: gitlib resources for ${{ parameters.PROJECT_NAME }}
        description: gitlab resources for ${{ parameters.PROJECT_NAME }}
        sourcePath: https://github.com/glamperi/devspaces-dotnet-web-api-sample
        repoVisibility: public

    - id: devspaces
      name: Create Dev Spaces workspace
      action: http:post
      input:
        url: https://devspaces.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/dashboard/api/workspaces
        headers:
          Content-Type: application/json
        body:
          name: ${{ parameters.PROJECT_NAME }}
          description: Dev Spaces workspace for ${{ parameters.PROJECT_NAME }}
  output:
    links:
      - title: GitLab Repository
        url: https://gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/development/${{ parameters.PROJECT_NAME }}
      - title: Dev Spaces Workspace
        url: https://devspaces.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/dashboard/workspaces/${{ parameters.PROJECT_NAME }}
