apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-web-api-sample
  title: .NET Web API Sample  - 3
  description: A sample .NET Web API project
spec:
  owner: your-team
  type: service
  parameters:
    - name: PROJECT_NAME
      description: The name of the project
      default: dotnet-web-api-sample
  steps:
    - id: template
      name: Fetch template
      action: fetch:template
      input:
        url: https://github.com/rafaeltuelho/devspaces-dotnet-web-api-sample
        values:
          projectName: ${{ parameters.PROJECT_NAME }}
  output:
    links:
      - title: Repository
        url: https://github.com/${{ parameters.PROJECT_NAME }}


