apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: my-dev-spaces-dotnet-webservice
  title:  My Dev Spaces DotNet Web API Sample
  description: DotNet WebService
  tags: ["net", "webservice"]
spec:
  type: service
  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
parameters:
  - name: PROJECT_NAME
    description: The name of the project
    default: my-project
  - name: DATABASE_USER
    description: The database username
    default: dbuser
resources:
  - name: my-service
    type: Service
    properties:
      name: ${PROJECT_NAME}-service
      ports:
        - 8080
  - name: my-deployment
    type: Deployment
    properties:
      name: ${PROJECT_NAME}-deployment
      replicas: 1
      containers:
        - name: my-container
          image: my-image:latest
          env:
            - name: DATABASE_USER
              value: ${DATABASE_USER}

