apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: devspaces-dotnet-web-api-sample
  title: dot net METAS 2
spec:
  type: template
  parameters:
    required:
      - name
    properties:
      name:
        title: Project Name
        type: string
        description: The name of the project
        default: dotnet-web-api-sample
      gitlabGroup:
        title: GitLab Group
        type: string
        description: The GitLab group where the project will be created
        default: user1
  steps:
    - id: clone-github-repo
      action: fetch:plain
      input:
        url: https://github.com/glamperi/${{ parameters.name }}.git
    - id: push-to-gitlab
      action: publish:gitlab
      input:
        repoUrl: https://gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/${{ parameters.gitlabGroup }}/${{ parameters.name }}.git
        repoName: ${{ parameters.name }}
        repoDescription: A sample .NET Web API repository
        repoVisibility: private
      dependsOn: [clone-github-repo]
    - id: create-devspaces-workspace
      action: devspaces:create-workspace
      input:
        workspaceName: ${{ parameters.name }}
        workspaceDescription: A sample .NET Web API workspace
        gitRepoUrl: https://gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/${{ parameters.gitlabGroup }}/${{ parameters.name }}.git
      dependsOn: [push-to-gitlab]
  outputs:
    - name: gitlabRepoUrl
      value: https://gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/${{ parameters.gitlabGroup }}/${{ parameters.name }}.git
    - name: devspacesWorkspaceUrl
      value: https://devspaces.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/${{ parameters.name }}
