apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: devspaces-dotnet-web-api-sample
  title: dot net METAS 16
spec:
  type: template
  parameters:
    required:
      - gitlabGroup
    properties:
      gitlabGroup:
        title: GitLab Group
        type: string
        description: The GitLab group where the project will be created
        default: user1
  steps:
    - id: clone-github-repo
      action: fetch:plain
      input:
        url: https://github.com/glamperi/devspaces-dotnet-web-api-sample.git
    - id: publish-gitlab-gitops
      name: Publish GitOps Repository to GitLab
      action: publish:gitlab
      input:
        sourcePath: https://github.com/glamperi/devspaces-dotnet-web-api-sample.git
        allowedHosts: gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com
        description: This is GitOps repository for ${{ parameters.name }}
        repoUrl: gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/${{ parameters.gitlabGroup }}/devspaces-dotnet-web-api-sample.git
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: "public"
    - id: create-devspaces-workspace
      action: devspaces:create-workspace
      input:
        workspaceName: devspaces-dotnet-web-api-sample
        workspaceDescription: A sample .NET Web API workspace
        gitRepoUrl: https://gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/${{ parameters.gitlabGroup }}/devspaces-dotnet-web-api-sample.git
      dependsOn: [publish-gitlab-gitops]
  outputs:
    - name: gitlabRepoUrl
      value: https://gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/${{ parameters.gitlabGroup }}/devspaces-dotnet-web-api-sample.git
    - name: devspacesWorkspaceUrl
      value: https://devspaces.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/devspaces-dotnet-web-api-sample

   
