apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: devspaces-dotnet-web-api-sample
  title: dot net METAS 9
spec:
  type: template
  parameters:
    required:
      - gitlabGroup
    properties:
      gitlabGroup:
        title: GitLab Group
        type: string
        description: The GitLab group where the project will be created
        default: user1
  steps:
    - id: clone-github-repo
      action: fetch:plain
      input:
        url: https://github.com/glamperi/devspaces-dotnet-web-api-sample.git
    - id: push-to-gitlab
      action: publish:gitlab
      input:
        integration: gitlab
        repoUrl: user1/devspaces-dotnet-web-api-sample.git
        repoName: devspaces-dotnet-web-api-sample
        repoDescription: A sample .NET Web API repository
        repoVisibility: private
      dependsOn: [clone-github-repo]
    - id: create-devspaces-workspace
      action: devspaces:create-workspace
      input:
        workspaceName: devspaces-dotnet-web-api-sample
        workspaceDescription: A sample .NET Web API workspace
        gitRepoUrl: https://gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/user1/devspaces-dotnet-web-api-sample.git
      dependsOn: [push-to-gitlab]
  outputs:
    - name: gitlabRepoUrl
      value: https://gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/user1/devspaces-dotnet-web-api-sample.git
    - name: devspacesWorkspaceUrl
      value: https://devspaces.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/devspaces-dotnet-web-api-sample
