apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-devspaces-dotnet-api
  title: Create DevSpaces Workspace for .NET API - 6
  description: Clones repo to GitLab and starts DevSpaces workspace
spec:
  owner: user1
  type: service
  parameters:
    - title: GitLab Repository Info
      required: []
      properties:
        targetRepo:
          type: string
          title: Target GitLab Repo URL
          default: https://gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/user1/devspaces-dotnet-web-api-sample.git

  steps:
    - id: clone-and-push
      name: Clone GitHub and Push to GitLab
      action: fetch:plain
      input:
        url: https://github.com/glamperi/devspaces-dotnet-web-api-sample.git


    - id: git-push
      name: Push to GitLab
      action: publish:gitlab
      input:
        repoUrl: gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/user1/devspaces-dotnet-web-api-sample
        defaultBranch: main
        gitAuthorName: "DevHub Automation"
        gitAuthorEmail: "devhub@example.com"

    - id: create-devspaces
      name: Create DevSpaces Workspace
      action: http:post
      input:
        url: https://devspaces.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/plugin/devspaces/create
        headers:
          Content-Type: application/json
        body:
          repoUrl: "${{ parameters.targetRepo }}"

  output:
    links:
      - title: GitLab Repository
        url: "${{ parameters.targetRepo }}"
      - title: DevSpaces Workspace
        url: "https://devspaces.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/#${{ parameters.targetRepo | base64 }}"
