apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-devspaces-dotnet-api
  title: Move to Target Repo & Create DevSpaces Workspace for .NET API
  description: Clones repo to GitLab and starts DevSpaces workspace
spec:
  owner: user1
  type: service

  parameters:
    - title: Repo Information
      required: [gitlabHost, repoOwner, repoName, cluster]
      properties:
        gitlabHost:
          type: string
          title: GitLab Host (no protocol)
          default: gitlab-gitlab.apps.cluster-54sqd.54sqd.sandbox2969.opentlc.com
        repoOwner:
          type: string
          title: GitLab Owner / Namespace
          default: user1
        repoName:
          type: string
          title: GitLab Repository Name
          default: devspaces-dotnet-web-api-sample
        cluster:
          type: string
          title: Cluster domain (e.g. .apps.cluster-xyz.abc.sandbox.opentlc.com)
          default: .apps.cluster-54sqd.54sqd.sandbox2969.opentlc.com
  steps:
    - id: fetch-template
      name: Fetch template
      action: fetch:template
      input:
        url: ../../skeleton_netapi
        targetPath: ./workspace
        values:
          component_id: ${{ parameters.repoName }}
          description: A .NET API demo project
          host: ${{ parameters.gitlabHost }}
          destination: ${{ parameters.repoOwner }}/${{ parameters.repoName }}
          cluster: ${{ parameters.cluster }}

    - id: publish
      name: Publish to GitLab
      action: publish:gitlab
      input:
        repoUrl: ${{ parameters.gitlabHost }}?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repoName }}
        defaultBranch: main
        gitAuthorName: DevHub Automation
        gitAuthorEmail: devhub@example.com
        sourcePath: ./workspace

    - id: register
      name: Register component in Backstage catalog
      action: catalog:register
      input:
        optional: true
        repoContentsUrl: "https://${{ parameters.gitlabHost }}/${{ parameters.repoOwner }}/${{ parameters.repoName }}"
        catalogInfoPath: catalog-info.yaml

  output:
    links:
      - title: GitLab Repository
        url: "https://${{ parameters.gitlabHost }}/${{ parameters.repoOwner }}/${{ parameters.repoName }}"
      - title: Open in DevSpaces
        url: "https://devspaces${{ parameters.cluster }}/dashboard/#https://${{ parameters.gitlabHost }}/${{ parameters.repoOwner }}/${{ parameters.repoName }}"

