apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-devspaces-dotnet-api
  title: Create DevSpaces Workspace for .NET API - 30
  description: Clones repo to GitLab and starts DevSpaces workspace
spec:
  owner: user1
  type: service
  parameters:
    - title: Repo Information
      required: [githubRepoUrl, gitlabHost, repoOwner, repoName]
      properties:
        githubRepoUrl:
          type: string
          title: GitHub Source Repository (URL)
          default: https://github.com/glamperi/devspaces-dotnet-web-api-sample.git
        gitlabHost:
          type: string
          title: GitLab Host (no protocol)
          default: gitlab-gitlab.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com
        repoOwner:
          type: string
          title: GitLab Owner / Namespace
          default: user1
        repoName:
          type: string
          title: GitLab Repository Name
          default: devspaces-dotnet-web-api-sample

  steps:
    - id: fetch-template
      name: Clone GitHub Repo
      action: fetch:plain
      input:
        url: ${{ parameters.githubRepoUrl }}

    - id: push-to-gitlab
      name: Push to GitLab
      action: publish:gitlab
      input:
        repoUrl: ${{ parameters.gitlabHost }}?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repoName }}
        defaultBranch: main
        gitAuthorName: "DevHub Automation"
        gitAuthorEmail: "devhub@example.com"

    - id: set-links
      name: Set Output Links
      action: debug:log
      input:
        message: "Preparing links"
      output:
        gitlabRepoUrl: "https://${{ parameters.gitlabHost }}/${{ parameters.repoOwner }}/${{ parameters.repoName }}"
        devspacesUrl: "https://devspaces.apps.cluster-vnfjq.vnfjq.sandbox1957.opentlc.com/#aHR0cHM6Ly9naXRsYWItZ2l0bGFiLmFwcHMuY2x1c3Rlci12bmZqcS52bmZqcS5zYW5kYm94MTk1Ny5vcGVudGxjLmNvbS91c2VyMS9kZXZzcGFjZXMtZG90bmV0LXdlYi1hcGktc2FtcGxl"


    - id: log-link
      name: Log DevSpaces Launch URL
      action: debug:log
      input:
        message: "DevSpaces launch URL: ${{ steps.set-links.output.devspacesUrl }}"

  output:
    links:
      - title: GitLab Repository
        url: "${{ steps.set-links.output.gitlabRepoUrl }}"
      - title: Open in DevSpaces
        url: "${{ steps.set-links.output.devspacesUrl }}"
